// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoK3Y6s-Y5c5yvgjH9Wh625jTyOdSYrMs',
    appId: '1:512576979473:web:4f8f542bc5189655c0a7b0',
    messagingSenderId: '512576979473',
    projectId: 'blogs-flutter-854cf',
    authDomain: 'blogs-flutter-854cf.firebaseapp.com',
    storageBucket: 'blogs-flutter-854cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2KpR6SxxclyTYBga8hCZIFzphxu8ymo4',
    appId: '1:512576979473:android:2bccb6a70859efdfc0a7b0',
    messagingSenderId: '512576979473',
    projectId: 'blogs-flutter-854cf',
    storageBucket: 'blogs-flutter-854cf.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: 'AIzaSyC2KpR6SxxclyTYBga8hCZIFzphxu8ymo4',
      appId: '1:512576979473:web:4f8f542bc5189655c0a7b0',
      messagingSenderId: '512576979473',
      projectId: 'blogs-flutter-854cf',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHZfaZecOylwPG4j8_zinM8yTbBvTtTgk',
    appId: '1:512576979473:ios:b3fe85ae2a2e8e52c0a7b0',
    messagingSenderId: '512576979473',
    projectId: 'blogs-flutter-854cf',
    storageBucket: 'blogs-flutter-854cf.appspot.com',
    iosBundleId: 'com.example.blog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHZfaZecOylwPG4j8_zinM8yTbBvTtTgk',
    appId: '1:512576979473:ios:c3da50456ceaf1fcc0a7b0',
    messagingSenderId: '512576979473',
    projectId: 'blogs-flutter-854cf',
    storageBucket: 'blogs-flutter-854cf.appspot.com',
    iosBundleId: 'com.example.blog.RunnerTests',
  );
}
